default_stages:
- commit
exclude: .git|.tox|tests|docs
fail_fast: true
repos:
- hooks:
  - exclude: ^tutorials/
    id: check-docstring-first
  - exclude: ^tutorials/
    id: trailing-whitespace
  - exclude: ^tutorials/
    id: end-of-file-fixer
  - id: check-toml
  - id: check-merge-conflict
  - id: check-added-large-files
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
- hooks:
  - id: black
  repo: https://github.com/psf/black
  rev: 21.12b0
- hooks:
  - id: isort
  repo: https://github.com/timothycrosley/isort
  rev: 5.10.1
- hooks:
  - additional_dependencies:
    - flake8-bugbear
    - flake8-implicit-str-concat
    id: flake8
  repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
- hooks:
  - args:
    - --no-strict-optional
    - --ignore-missing-imports
    id: mypy
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.931
- hooks:
  - args:
    - --sync
    - tutorials/*.ipynb
    files: ^tutorials/
    id: jupytext
  repo: https://github.com/mwouts/jupytext
  rev: v1.13.5

- hooks:
  - id: commitizen
    stages: [commit-msg]
  repo: https://github.com/commitizen-tools/commitizen
  rev: master

- hooks:
  - entry: python custom_hook.py
    id: custom_hook
    language: python
    name: custom_hook
    verbose: true
  repo: local
