exclude: '.git|.tox|tests|docs'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-docstring-first
        exclude: ^tutorials/
      - id: trailing-whitespace
        exclude: ^tutorials/
      - id: end-of-file-fixer
        exclude: ^tutorials/
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
      - id: isort

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-implicit-str-concat

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]

  - repo: https://github.com/mwouts/jupytext
    rev: v1.13.5
    hooks:
    - id: jupytext
      files: ^tutorials/
      args: [--sync, 'tutorials/*.ipynb']


  - repo: local
    hooks:
    - id: custom_hook
      name: custom_hook
      entry: python custom_hook.py
      language: python
      verbose: true
