data:
    data_directory:
    train_batch_size: 128
task:
  max_seq_len: 1024
  max_predictions_per_seq: 200
trainer:
  dtype: bf16
  num_gpus: 0
  tpu_address:
  epochs: 20
  strategy: mirrored
  steps_per_epoch: 50000
  model_checkpoint_dir:
  callback_steps: 10000
optimizer:
  learning_rate: 1e-4
  warmup_rate: 0.2
  loss_type:
  use_constant_lr: false
model:
  is_training: true
  use_dropout: true
  num_layers: 12
