task:
  name: tft

data:
  name: xsum
  take_sample: false
  batch_size: 32
  max_length: 512

model:
  name: t5-small
  type: textdecoder_saved_model

text_generation:
  max_iterations: 64
  mode: greedy
