task:
  name: tft

data:
  name: cnn_dailymail
  take_sample: false
  batch_size: 32
  max_length: 512

model:
  name: gpt2
  type: textdecoder_saved_model

text_generation:
  max_iterations: 64
  mode: greedy
