name: Documentation Build
on:
  workflow_run:
    workflows: ["ci-cd"]
    types:
      - completed
  push:
    branches: [ main ]
    tags: '*'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Build documentation
      run: |
        mkdir gh-pages
        touch gh-pages/.nojekyll
        cd docs/
        pip3 install -r requirements_build.txt
        make clean html
        cp -r * ../gh-pages/
    - name: Deploy documentation
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: gh-pages
