name: Release
on: 
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Set tag
      run: git tag ${{ github.event.inputs.version }}
      run: echo "Tag is ${{ github.event.inputs.version }}"
    - name: Patch version
      run: |
        pip install python-semantic-release
        pip install absl-py
        python patch_version.py
        semantic-release changelog -v DEBUG