name: Release
on: 
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get tag
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Patch version
      run: |
        echo "Tag retrived is ${{ steps.vars.outputs.tag }}"
        pip install python-semantic-release
        pip install absl-py
        python patch_version.py ${{ steps.vars.outputs.tag }}
        semantic-release changelog -v DEBUG